'use strict';
const DURATION=15*60, STORAGE_KEY='escapeRoomBest_v1';
const $=id=>document.getElementById(id);
const all=selector=>[...document.querySelectorAll(selector)];
const solution={clock:[1,3,7,9,11],painting:4,book:'الحفرة',box:'2',desk:'32',safe:'6429',door:'173'};
const digits={clock:6,painting:4,box:2,desk:9};
const hints={clock:'ابدأ بأصغر رقم ثم الأكبر، واحدًا تلو الآخر.',painting:'الرقم المطلوب هو الأوضح لمعانًا.',book:'فكر في شيء يكبر عندما تزيل منه التراب.',box:'انظر إلى الرمز ★ في قائمة الشفرة.',desk:'كل حد يساوي ضعف الذي قبله.',safe:'رتب الأرقام: الساعة ثم اللوحة ثم الصندوق ثم المكتب.',door:'رمز الباب مكتوب على الورقة التي داخل الخزنة.'};
let game=null,toastTimeout;
function freshGame(){return{deadline:Date.now()+DURATION*1000,timer:null,timeLeft:DURATION,score:1000,hintsLeft:3,hintsUsed:0,hinted:new Set(),inventory:new Set(),solved:new Set(),clues:[],openedAt:{},current:null,finished:false,clockProgress:[],paintingTarget:0};}
function screen(id){all('.screen').forEach(el=>el.classList.toggle('active',el.id===id));window.scrollTo(0,0);}
function modal(id){$(id).classList.remove('hidden');const close=$(id).querySelector('.modal-close');if(close)close.focus();}
function close(id){$(id).classList.add('hidden');if(game)game.current=null;}
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.add('hidden'),2600);}
function time(seconds){return Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0');}
function shake(el){el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');}
function feedback(key,message,wrong=false){const el=$(key+'-feedback');el.textContent=message;el.classList.toggle('error',wrong);if(wrong)shake(el);}
function score(delta){game.score=Math.max(0,game.score+delta);$('score-text').textContent=game.score;}
function clue(html,obj){game.clues.push(html);const li=document.createElement('li');li.innerHTML=html;$('clue-list').appendChild(li);$('notebook-badge').textContent=game.clues.length;$('notebook-badge').classList.remove('hidden');if(obj)$(obj).classList.add('solved');toast('عثرت على دليل جديد ✦');}
function solve(key,obj){if(game.solved.has(key))return false;game.solved.add(key);$(obj).classList.add('solved');const elapsed=(Date.now()-(game.openedAt[key]||Date.now()))/1000;const bonus=elapsed<15?80:elapsed<30?50:elapsed<60?20:0;score(bonus);$('progress-fill').style.width=(game.solved.size/6*100)+'%';$('progress-text').textContent=game.solved.size+' من ٦ ألغاز';return true;}
function openPuzzle(key){if(!game||game.finished)return;game.current=key;game.openedAt[key]??=Date.now();modal('modal-'+key);}
function useHint(){if(!game?.current||!hints[game.current])return toast('افتح أحد الألغاز أولًا لتحصل على تلميح.');const key=game.current;if(game.solved.has(key))return toast('لقد حللت هذا اللغز بالفعل.');if(game.hinted.has(key))return toast('التلميح ظاهر في نافذة اللغز.');if(game.hintsLeft===0)return toast('لا توجد تلميحات متبقية.');game.hinted.add(key);game.hintsLeft--;game.hintsUsed++;score(-50);$('hints-count').textContent=game.hintsLeft;$(key+'-hint').textContent='💡 '+hints[key];toast('استخدمت تلميحًا: −٥٠ نقطة');}
function shuffled(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function buildClock(){const row=$('clock-chips');row.replaceChildren();game.clockProgress=[];for(const n of shuffled(solution.clock)){const btn=document.createElement('button');btn.type='button';btn.className='chip';btn.textContent=n;btn.addEventListener('click',()=>{if(game.solved.has('clock'))return;if(n===solution.clock[game.clockProgress.length]){game.clockProgress.push(n);btn.disabled=true;btn.classList.add('picked');if(game.clockProgress.length===5){solve('clock','obj-clock');feedback('clock','أحسنت! رتبت الأرقام بشكل صحيح.');clue('رقم الساعة: <strong>٦</strong>','obj-clock');setTimeout(()=>close('modal-clock'),1000);}}else{game.clockProgress=[];row.querySelectorAll('button').forEach(b=>{b.disabled=false;b.classList.remove('picked');});feedback('clock','الترتيب غير صحيح. حاول مجددًا.',true);}});row.appendChild(btn);}}
function buildPainting(){const row=$('painting-grid');row.replaceChildren();game.paintingTarget=Math.floor(Math.random()*12);const decoys=shuffled([7,1,9,5,8,3,6,2,9,5,1]);for(let i=0;i<12;i++){const target=i===game.paintingTarget;const btn=document.createElement('button');btn.type='button';btn.className='num-cell '+(target?'target':'faint');btn.textContent=target?'4':decoys.pop();btn.addEventListener('click',()=>{if(game.solved.has('painting'))return;if(target){solve('painting','obj-painting');feedback('painting','وجدت الرقم المحفور!');clue('رقم خلف اللوحة: <strong>٤</strong>','obj-painting');$('obj-safe').classList.remove('hidden');setTimeout(()=>close('modal-painting'),1000);}else feedback('painting','هذا ليس الرقم المطلوب.',true);});row.appendChild(btn);}}
function buildBook(){const row=$('book-options');row.replaceChildren();for(const answer of shuffled(['الحفرة','الماء','الوقت','الضوء'])){const btn=document.createElement('button');btn.type='button';btn.textContent=answer;btn.addEventListener('click',()=>{if(game.solved.has('book'))return;if(answer===solution.book){btn.classList.add('correct');solve('book','obj-book');game.inventory.add('key');$('inv-items').innerHTML='<span class="inv-chip">🔑 مفتاح صغير</span>';feedback('book','إجابة صحيحة! وجدت مفتاحًا داخل الكتاب.');clue('مفتاح صغير داخل الكتاب؛ يفتح الصندوق.','obj-book');setTimeout(()=>close('modal-book'),1200);}else{btn.classList.add('wrong');feedback('book','إجابة خاطئة؛ حاول مجددًا.',true);setTimeout(()=>btn.classList.remove('wrong'),600);}});row.appendChild(btn);}}
function normalized(value){return value.trim().replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776));}
function boxSubmit(){if(game.solved.has('box'))return;if(normalized($('box-answer').value)==='2'){solve('box','obj-box');$('obj-box').classList.add('opened');feedback('box','فككت الشفرة!');clue('رقم ورقة الصندوق: <strong>٢</strong>','obj-box');setTimeout(()=>close('modal-box'),1000);}else feedback('box','رقم غير صحيح، راجع الرموز.',true);}
function deskSubmit(){if(game.solved.has('desk'))return;if(normalized($('desk-answer').value)==='32'){solve('desk','obj-desk');$('desk-stage-question').classList.add('hidden');$('desk-stage-note').classList.remove('hidden');feedback('desk','انفتح الدرج!');clue('رقم المكتب: <strong>٩</strong>، وفي الدرج ورقة ترتيب الخزنة.','obj-desk');}else feedback('desk','تأمل نمط الأعداد وحاول مرة أخرى.',true);}
function joined(ids){return ids.map(id=>normalized($(id).value)).join('');}
function safeSubmit(){if(game.solved.has('safe'))return;if(!['clock','painting','box','desk'].every(key=>game.solved.has(key)))return feedback('safe','اجمع الأدلة الأربعة أولًا لفتح الخزنة.',true);if(joined(['safe-d1','safe-d2','safe-d3','safe-d4'])===solution.safe){solve('safe','obj-safe');$('safe-stage-lock').classList.add('hidden');$('safe-stage-note').classList.remove('hidden');feedback('safe','فتحت الخزنة وعثرت على الرمز الأخير!');clue('رمز الباب: <strong dir="ltr">173</strong>','obj-safe');}else feedback('safe','الرمز غير صحيح.',true);}
function doorSubmit(){if(!game.solved.has('safe'))return feedback('door','افتح الخزنة أولًا لتحصل على رمز الباب.',true);if(joined(['door-d1','door-d2','door-d3'])===solution.door){$('obj-door').classList.add('opened');feedback('door','الباب يفتح الآن…');setTimeout(()=>{close('modal-door');win();},750);}else feedback('door','الرمز غير صحيح.',true);}
function timerTick(){if(!game||game.finished)return;game.timeLeft=Math.max(0,Math.ceil((game.deadline-Date.now())/1000));$('timer-text').textContent=time(game.timeLeft);$('hud-timer').classList.toggle('danger',game.timeLeft<=60);if(game.timeLeft===0){clearInterval(game.timer);game.finished=true;all('.modal-overlay').forEach(m=>m.classList.add('hidden'));screen('screen-lose');}}
function best(){try{const b=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{score:Number(b.score)||0,time:Number.isFinite(b.time)?b.time:null};}catch{return{score:0,time:null};}}
function renderBest(){const b=best();$('best-stats').innerHTML=b.score||b.time!==null?'<span>أفضل نتيجة: <b>'+b.score+'</b> نقطة</span><span>أسرع وقت: <b>'+(b.time!==null?time(b.time):'—')+'</b></span>':'';}
function win(){if(game.finished)return;timerTick();if(game.finished)return;game.finished=true;clearInterval(game.timer);const elapsed=DURATION-game.timeLeft;score(Math.floor(game.timeLeft/10));$('win-time').textContent=time(elapsed);$('win-hints').textContent=game.hintsUsed;$('win-score').textContent=game.score;const b=best();const record=game.score>b.score||b.time===null||elapsed<b.time;b.score=Math.max(b.score,game.score);b.time=b.time===null?elapsed:Math.min(elapsed,b.time);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(b));}catch{}$('win-record').classList.toggle('hidden',!record);renderBest();screen('screen-win');}
function start(){if(game?.timer)clearInterval(game.timer);all('.modal-overlay').forEach(m=>m.classList.add('hidden'));game=freshGame();$('score-text').textContent='1000';$('hints-count').textContent='٣';$('notebook-badge').classList.add('hidden');$('clue-list').innerHTML='<li>لم تجد أي أدلة بعد. فتش الغرفة جيدًا.</li>';$('inv-items').innerHTML='<span class="muted">لا شيء بعد</span>';$('progress-fill').style.width='0';$('progress-text').textContent='٠ من ٦ ألغاز';$('obj-safe').classList.add('hidden');all('.room-object').forEach(el=>el.classList.remove('solved','opened'));all('.feedback,.hint-line').forEach(el=>{el.textContent='';el.classList.remove('error');});all('input').forEach(el=>el.value='');$('desk-stage-question').classList.remove('hidden');$('desk-stage-note').classList.add('hidden');$('safe-stage-lock').classList.remove('hidden');$('safe-stage-note').classList.add('hidden');buildClock();buildPainting();buildBook();screen('screen-game');timerTick();game.timer=setInterval(timerTick,250);}
function digitInputs(ids,submit){ids.forEach((id,index)=>{const el=$(id);el.addEventListener('input',()=>{el.value=normalized(el.value).replace(/\D/g,'').slice(0,1);if(el.value&&index<ids.length-1)$(ids[index+1]).focus();else if(el.value&&ids.every(key=>$(key).value))submit();});el.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!el.value&&index>0)$(ids[index-1]).focus();if(e.key==='Enter')submit();});});}
document.addEventListener('DOMContentLoaded',()=>{
  $('btn-start').addEventListener('click',start);$('btn-replay').addEventListener('click',start);$('btn-retry').addEventListener('click',start);$('btn-howto').addEventListener('click',()=>modal('modal-howto'));$('btn-notebook').addEventListener('click',()=>modal('modal-notebook'));$('btn-hint').addEventListener('click',useHint);
  all('[data-close]').forEach(el=>el.addEventListener('click',()=>close(el.dataset.close)));all('.modal-overlay').forEach(el=>el.addEventListener('click',e=>{if(e.target===el)close(el.id);}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const opened=all('.modal-overlay:not(.hidden)').at(-1);if(opened)close(opened.id);}});
  for(const key of ['clock','painting','book','desk','safe','door'])$('obj-'+key).addEventListener('click',()=>openPuzzle(key));
  $('obj-box').addEventListener('click',()=>game.inventory.has('key')?openPuzzle('box'):modal('modal-box-locked'));
  $('box-submit').addEventListener('click',boxSubmit);$('desk-submit').addEventListener('click',deskSubmit);$('safe-submit').addEventListener('click',safeSubmit);$('door-submit').addEventListener('click',doorSubmit);
  $('box-answer').addEventListener('keydown',e=>{if(e.key==='Enter')boxSubmit();});$('desk-answer').addEventListener('keydown',e=>{if(e.key==='Enter')deskSubmit();});
  digitInputs(['safe-d1','safe-d2','safe-d3','safe-d4'],safeSubmit);digitInputs(['door-d1','door-d2','door-d3'],doorSubmit);renderBest();
});
